- name: Update apt cache
  sudo: true
  apt: update_cache=yes

- name: Install required packages
  sudo: true
  apt: pkg={{ item }}
  with_items:
    - nginx
    - postgresql
    - git
    - python-virtualenv
    - python-dev
    - postgresql-server-dev-9.1