- hosts: server
  pre_tasks:
    - name: Load passwords
      include_vars: "vars/passwords.yml"
  roles:
    - packages
    - db

- hosts: server
  pre_tasks:
    - name: Load variables
      include_vars: "vars/{{ app }}"
  roles:
    - code
    - build
    - nginx
