- hosts: server
  tasks:

    - name: Task one
      command: shuf -i1-100 -n1
      register: whatisit

    - name: Task two
      command: echo {{ whatisit }}

    - name: Task three
      command: echo "blah"
      when: whatisit.changed