- hosts: server
  tasks:
    - name: Load passwords
      include_vars: "vars/passwords.yml"

- include: provision.yml
- include: app.yml app=facetweet
- include: app.yml app=hackerit

- hosts: server
  roles:
    - { role: db_restore, app: 'facetweet' }
    - { role: db_restore, app: 'hackerit' }
